name: Update Plugins v0.2

on:
  schedule:
    - cron: "25 0,3,7,11,15,18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-plugins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Bi-Monthly Log Reset
      run: |
        if [ "$(date +%d)" = "01" ] && [ $((10#$(date +%m) % 2)) -eq 0 ]; then
          echo "--- Log Rotated on $(date) ---" > update_log.txt
        else
          echo "Skipping log reset."
        fi

    - name: Run Plugin Sync Script
      run: python update_repo.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated plugin configuration and log sync"
